import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Platform, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View, Image } from 'react-native';
import { useAuth } from '../context-auth';
import { useCart } from '../context-cart';

const API='http://119.59.102.161:3099/api';
const C={bg:'#FFF8FA',white:'#FFF',ink:'#2D2025',muted:'#7E6870',pink:'#E75480',pinkDark:'#C83D68',border:'#EBCFD8',soft:'#FFF0F4'};
const notify=(t:string,m:string)=>Platform.OS==='web'?window.alert(`${t}\n\n${m}`):Alert.alert(t,m);

export default function Checkout(){
 const {token}=useAuth(); const {items,total,clearCart}=useCart();
 const [first,setFirst]=useState(''); const [last,setLast]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState(''); const [address,setAddress]=useState(''); const [loading,setLoading]=useState(false);
 const submit=async()=>{if(items.length===0){notify('ตะกร้าว่าง','กรุณาเลือกสินค้าอย่างน้อย 1 รายการ');router.back();return}if(!first.trim()||!last.trim()||!phone.trim()||!address.trim()){notify('ข้อมูลไม่ครบ','กรุณากรอกชื่อ นามสกุล เบอร์โทร และที่อยู่');return}if(!token){router.replace('/login');return}setLoading(true);try{const orderItems=items.map(item=>item.item_type==='Cat'?{item_type:'Cat',cat_id:Number(item.cat_id),quantity:1}:{item_type:'Product',product_id:Number(item.product_id),quantity:Math.max(1,item.quantity)});const r=await fetch(API+'/orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({first_name:first.trim(),last_name:last.trim(),phone:phone.trim(),email:email.trim()||null,address:address.trim(),items:orderItems})});const d=await r.json();if(!r.ok)throw new Error(d.message||'สร้างคำสั่งซื้อไม่สำเร็จ');clearCart();router.replace({pathname:'/payment',params:{orderId:String(d.order_id),total:String(d.total_amount)}} as any)}catch(e){notify('สั่งซื้อไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด')}finally{setLoading(false)}};
 return <SafeAreaView style={s.container}><StatusBar barStyle="dark-content" backgroundColor={C.bg}/><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={25} color={C.pink}/></TouchableOpacity><View><Text style={s.title}>ชำระเงิน</Text><Text style={s.sub}>{items.length} รายการ</Text></View><View style={{width:25}}/></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.step}><View style={s.stepActive}><Text style={s.stepNumActive}>1</Text></View><Text style={s.stepText}>รายการ</Text><View style={s.stepLine}/><View style={s.stepActive}><Text style={s.stepNumActive}>2</Text></View><Text style={s.stepText}>ข้อมูลจัดส่ง</Text><View style={s.stepLine}/><View style={s.stepInactive}><Text style={s.stepNum}>3</Text></View><Text style={s.stepMuted}>ชำระเงิน</Text></View>
  <View style={s.card}><Text style={s.section}>รายการสั่งซื้อ ({items.length})</Text>{items.map(item=><View key={item.key} style={s.itemRow}>{item.image_url?<Image source={{uri:item.image_url}} style={s.image}/>:<View style={s.iconBox}><Ionicons name={item.item_type==='Cat'?'paw-outline':'cube-outline'} size={25} color={C.pink}/></View>}<View style={{flex:1}}><Text style={s.itemName}>{item.name}</Text><Text style={s.muted}>{item.quantity} × ฿{Number(item.price).toLocaleString()}</Text></View><Text style={s.lineTotal}>฿{(Number(item.price)*item.quantity).toLocaleString()}</Text></View>)}<View style={s.total}><Text style={s.totalLabel}>ยอดรวม</Text><Text style={s.totalValue}>฿{total.toLocaleString()}</Text></View></View>
  <View style={s.card}><Text style={s.section}>ข้อมูลผู้สั่งซื้อ</Text>{[['ชื่อ',first,setFirst,'First name'],['นามสกุล',last,setLast,'Last name'],['เบอร์โทร',phone,setPhone,'08xxxxxxxx'],['อีเมล (ถ้ามี)',email,setEmail,'email@example.com']].map(([label,val,setter,ph]:any)=><View key={label}><Text style={s.label}>{label}</Text><TextInput value={val} onChangeText={setter} placeholder={ph} placeholderTextColor="#B49BA4" style={s.input}/></View>)}<Text style={s.label}>ที่อยู่จัดส่ง</Text><TextInput value={address} onChangeText={setAddress} placeholder="บ้านเลขที่ ถนน ตำบล อำเภอ จังหวัด รหัสไปรษณีย์" placeholderTextColor="#B49BA4" multiline style={[s.input,s.area]}/></View>
  <TouchableOpacity style={[s.button,loading&&{opacity:.6}]} onPress={submit} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<><Text style={s.buttonText}>ดำเนินการชำระเงิน</Text><Ionicons name="arrow-forward" size={18} color="#fff"/></>}</TouchableOpacity>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:C.bg},header:{height:68,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:C.border,backgroundColor:C.white},title:{fontSize:20,fontWeight:'900',color:C.ink},sub:{fontSize:11,color:C.muted},content:{width:'100%',maxWidth:800,alignSelf:'center',padding:20,paddingBottom:50},step:{flexDirection:'row',alignItems:'center',marginBottom:18},stepActive:{width:30,height:30,borderRadius:15,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'},stepInactive:{width:30,height:30,borderRadius:15,backgroundColor:C.soft,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},stepNum:{color:C.muted,fontWeight:'900'},stepNumActive:{color:'#fff',fontWeight:'900'},stepText:{fontSize:11,fontWeight:'900',color:C.pink,marginLeft:6},stepMuted:{fontSize:11,color:C.muted,marginLeft:6},stepLine:{flex:1,height:1,backgroundColor:C.border,marginHorizontal:7},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,padding:18,marginBottom:14},section:{fontSize:17,fontWeight:'900',color:C.ink,marginBottom:14},itemRow:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:8},image:{width:58,height:58,backgroundColor:C.soft},iconBox:{width:58,height:58,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},itemName:{fontSize:13,fontWeight:'900',color:C.ink},muted:{fontSize:11,color:C.muted,marginTop:3},lineTotal:{fontSize:13,fontWeight:'900',color:C.ink},total:{borderTopWidth:1,borderColor:C.border,marginTop:12,paddingTop:14,flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontWeight:'800',color:C.muted},totalValue:{fontSize:22,fontWeight:'900',color:C.pinkDark},label:{fontSize:12,fontWeight:'900',color:C.ink,marginTop:11,marginBottom:5},input:{height:46,borderWidth:1,borderColor:C.border,backgroundColor:'#FFFBFC',paddingHorizontal:12,color:C.ink,fontSize:13},area:{height:90,paddingTop:12,textAlignVertical:'top'},button:{height:52,backgroundColor:C.pink,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:9},buttonText:{color:'#fff',fontWeight:'900',fontSize:14}});
