import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, Alert } from 'react-native';

const API_URL = 'http://localhost:3099/api'; // Android emulator: http://10.0.2.2:3099/api
const COLORS = { primary:'#EC4899', background:'#FFF', surface:'#FFF1F2', border:'#FFE4E6', text:'#3F3F46', secondary:'#A1A1AA' };
type Product = { product_id:number; product_name:string; category:string; description?:string; price:number; stock_quantity:number; image_url?:string };

export default function HomeScreen() {
  const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [screen,setScreen]=useState<'list'|'form'>('list'); const [editing,setEditing]=useState<Product|null>(null); const [search,setSearch]=useState('');
  const [form,setForm]=useState({product_name:'',category:'',description:'',price:'',stock_quantity:'',image_url:''});
  const load=async()=>{try{setLoading(true);const r=await fetch(`${API_URL}/products`);if(!r.ok)throw Error('โหลดข้อมูลสินค้าไม่สำเร็จ');setProducts(await r.json());setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const openForm=(p?:Product)=>{setEditing(p||null);setForm(p?{product_name:p.product_name,category:p.category,description:p.description||'',price:String(p.price),stock_quantity:String(p.stock_quantity),image_url:p.image_url||''}:{product_name:'',category:'',description:'',price:'',stock_quantity:'',image_url:''});setScreen('form')};
  const save=async()=>{if(!form.product_name||!form.category||!form.price)return Alert.alert('กรุณากรอกชื่อสินค้า หมวดหมู่ และราคา');try{const r=await fetch(`${API_URL}/products${editing?`/${editing.product_id}`:''}`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:Number(form.price),stock_quantity:Number(form.stock_quantity||0)})});if(!r.ok)throw Error('บันทึกสินค้าไม่สำเร็จ');await load();setScreen('list')}catch(e:any){Alert.alert('Error',e.message)}};
  const filtered=products.filter(p=>`${p.product_name} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color={COLORS.primary}/><Text>Loading products...</Text></View>;
  if(screen==='form')return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.form}><Text style={styles.title}>{editing?'Edit Product':'Add Product'}</Text>{[['product_name','Product Name'],['category','Category'],['description','Description'],['price','Price'],['stock_quantity','Stock Quantity'],['image_url','Image URL']].map(([key,label])=><View style={styles.group} key={key}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,key==='description'&&styles.area]} multiline={key==='description'} keyboardType={key==='price'||key==='stock_quantity'?'numeric':'default'} value={(form as any)[key]} onChangeText={v=>setForm({...form,[key]:v})}/></View>)}<View style={styles.row}><TouchableOpacity style={styles.cancel} onPress={()=>setScreen('list')}><Text>Cancel</Text></TouchableOpacity><TouchableOpacity style={styles.save} onPress={save}><Text style={{color:'#fff',fontWeight:'700'}}>{editing?'Update':'Save'}</Text></TouchableOpacity></View></ScrollView></SafeAreaView>;
  return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.title}>Product Management</Text><TouchableOpacity style={styles.add} onPress={()=>openForm()}><Text style={{color:'#fff',fontWeight:'700'}}>+ Add</Text></TouchableOpacity></View><View style={styles.search}><Ionicons name="search" size={18} color={COLORS.secondary}/><TextInput placeholder="Search products..." style={{flex:1,marginLeft:8}} value={search} onChangeText={setSearch}/></View>{error?<Text style={styles.error}>{error} <Text onPress={load}>Retry</Text></Text>:<FlatList data={filtered} keyExtractor={p=>String(p.product_id)} contentContainerStyle={{padding:16}} renderItem={({item})=><View style={styles.card}>{item.image_url?<Image source={{uri:item.image_url}} style={styles.image}/>:null}<View style={{flex:1}}><Text style={styles.name}>{item.product_name}</Text><Text>{item.category}</Text><Text>฿{Number(item.price).toFixed(2)} | Stock: {item.stock_quantity}</Text></View><TouchableOpacity onPress={()=>openForm(item)}><Ionicons name="create-outline" size={24} color={COLORS.primary}/></TouchableOpacity></View>}/>}</SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},center:{flex:1,justifyContent:'center',alignItems:'center'},header:{padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:COLORS.border},title:{fontSize:24,fontWeight:'700',color:COLORS.primary},add:{backgroundColor:COLORS.primary,padding:12,borderRadius:10},search:{margin:16,padding:12,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,borderRadius:10,flexDirection:'row',alignItems:'center'},card:{padding:14,borderWidth:1,borderColor:COLORS.border,borderRadius:12,marginBottom:12,flexDirection:'row',alignItems:'center',gap:12},image:{width:70,height:70,borderRadius:8},name:{fontSize:17,fontWeight:'700',color:COLORS.text},form:{padding:22},group:{marginBottom:16},label:{fontWeight:'600',marginBottom:7,color:COLORS.text},input:{borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,borderRadius:10,padding:12,height:48},area:{height:90,textAlignVertical:'top'},row:{flexDirection:'row',gap:12,marginTop:10},cancel:{flex:1,padding:15,alignItems:'center',backgroundColor:'#eee',borderRadius:10},save:{flex:1,padding:15,alignItems:'center',backgroundColor:COLORS.primary,borderRadius:10},error:{padding:20,color:'red'}});
